FROM node:17-bullseye

ENV NODE_OPTIONS="--openssl-legacy-provider"

ENV DAPPER_ENV HARVESTER_API
ENV DAPPER_SOURCE /app
#ENV DAPPER_OUTPUT ./bin ./dist
ENV DAPPER_DOCKER_SOCKET true
ENV DAPPER_RUN_ARGS "-p 8005:8005 -v harvester-dashboard-cache:/app/node_modules"


ENV HOME ${DAPPER_SOURCE}
WORKDIR ${DAPPER_SOURCE}

ENTRYPOINT ["./scripts/entry"]
CMD ["default"]
